---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - stable
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "C78vOwW6YqKqSRYr+z2Rus2UsWaq57ntFKuORFo8UKw4eK5Nfbr4ysx5n47j0nyGE6SFGEGzlSQZtoHHQFzv6KTkK8PIkrewYLK8ESeEr09EjTgUjeU0olDHioMiI5z3xrb1rbLEVfOY/axyqRovKgqlTIRf8eRm0jdlNaFJ9v8bgxNMylKG24sezNhO+ORon66lYXrsZ10bd9mPyC4zYr5pV1OQjbxV1VB0ym3abRVSvlOtTUkG98ILLuO6FpHPbVYJcnnrDoTWvt2JxPkIECM2WShOlsiQdncO33CbOca6z6B6VYUAzPo1uzzsGn71MqeQV/wnqIZNj31F1wdSu72LxdjUfJSrKFnKckJGdxiS56OhFmC6v5YZeylruucUGM5dwpoKtH6SiR9QpoGWEkhrhTHyGa2QAoQovk1XRw0WQ7GrzpYK1LPOstuL37dPQLhENZ0O9yd0Tsm3YBzFSDP9J5lCyRuZv4ENDutxWs/oiGTNRp47PHYdANH7USG83UOpwSImZGQWBzWdSwfsWeGV4E0T0LLNSwVi5HeBSdTa+YAd62/PHaB5u+hDmcKEUodjWwMwUylO1m4wjqCinegC/RGkSLH2h3j8kUlWOSnyTrKhczyEaISixQsYBf1qwIj9nRf3XMHzXyxuBlqmNeHb9OZjD8lw8mLEmtlbBeI="
    file:
      - cross/img-linux-amd64.md5
      - cross/img-linux-amd64.sha256
      - cross/img-linux-amd64
    skip_cleanup: true
    on:
      go: stable
      tags: true
